from .IRender import IRender
from .IUpdate import IUpdate
from .IHandleEvents import IHandleEvents
from .IMaterial import IMaterial
from .IStateDependent import IStateDependent
from .IMove import IMove
from .IJump import IJump
from .IFall import IFall
from .ISpeed import ISpeed
